-- AlterTable
ALTER TABLE "clientes_config" ALTER COLUMN "maxUsuarios" SET DEFAULT 999999,
ALTER COLUMN "maxStorageGB" SET DEFAULT 999999,
ALTER COLUMN "maxLicitacoesMes" SET DEFAULT 999999,
ALTER COLUMN "maxAnalisesMes" SET DEFAULT 999999;
